# Generated by Django 4.2 on 2025-02-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='field',
            field=models.CharField(choices=[('component', 'Component'), ('brand', 'Brand'), ('price', 'Price'), ('description', 'Description')], max_length=255),
        ),
    ]
