# Generated by Django 4.2 on 2025-02-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_questions_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='audio',
            field=models.TextField(blank=True, null=True, verbose_name='Audio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='battery',
            field=models.TextField(blank=True, null=True, verbose_name='Batería'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.TextField(blank=True, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='product',
            name='certifications',
            field=models.TextField(blank=True, null=True, verbose_name='Certificaciones'),
        ),
        migrations.AlterField(
            model_name='product',
            name='connections',
            field=models.TextField(blank=True, null=True, verbose_name='Conexiones'),
        ),
        migrations.AlterField(
            model_name='product',
            name='general',
            field=models.TextField(blank=True, null=True, verbose_name='General'),
        ),
        migrations.AlterField(
            model_name='product',
            name='graphics',
            field=models.TextField(blank=True, null=True, verbose_name='Gráficos'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hard_disk',
            field=models.TextField(blank=True, null=True, verbose_name='Disco duro'),
        ),
        migrations.AlterField(
            model_name='product',
            name='keyboard',
            field=models.TextField(blank=True, null=True, verbose_name='Teclado'),
        ),
        migrations.AlterField(
            model_name='product',
            name='memory_reader',
            field=models.TextField(blank=True, null=True, verbose_name='Lector de tarjetas de memoria'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.TextField(blank=True, null=True, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='optical_driver',
            field=models.TextField(blank=True, null=True, verbose_name='Unidad óptica'),
        ),
        migrations.AlterField(
            model_name='product',
            name='packing_size',
            field=models.TextField(blank=True, null=True, verbose_name='Tamaño del embalaje'),
        ),
        migrations.AlterField(
            model_name='product',
            name='processor',
            field=models.TextField(blank=True, null=True, verbose_name='Procesador'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.TextField(blank=True, null=True, verbose_name='Código del producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.TextField(blank=True, null=True, verbose_name='RAM'),
        ),
        migrations.AlterField(
            model_name='product',
            name='screen',
            field=models.TextField(blank=True, null=True, verbose_name='Pantalla'),
        ),
        migrations.AlterField(
            model_name='product',
            name='so_software',
            field=models.TextField(blank=True, null=True, verbose_name='Sistema operativo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.TextField(blank=True, null=True, verbose_name='Garantía'),
        ),
        migrations.AlterField(
            model_name='product',
            name='webcam',
            field=models.TextField(blank=True, null=True, verbose_name='Webcam'),
        ),
    ]
