# Generated by Django 4.2 on 2025-02-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_audio_alter_product_battery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('price', 'Price'), ('product_name', 'Product Name'), ('brand', 'Brand'), ('model', 'Model'), ('product_code', 'Product Code'), ('processor', 'Processor'), ('graphics', 'Graphics'), ('hard_disk', 'Hard Disk'), ('ram', 'RAM'), ('screen', 'Screen'), ('battery', 'Battery'), ('warranty', 'Warranty'), ('so_software', 'SO/Software'), ('general', 'General'), ('connections', 'Connections'), ('audio', 'Audio'), ('webcam', 'Webcam'), ('certifications', 'Certifications'), ('packing_size', 'Packing Size'), ('memory_reader', 'Memory Reader'), ('keyboard', 'Keyboard'), ('optical_driver', 'Optical Driver')], max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='field',
            new_name='intent',
        ),
        migrations.AddField(
            model_name='questions',
            name='entidades',
            field=models.ManyToManyField(to='store.entity'),
        ),
    ]
