# Generated by Django 4.2 on 2025-02-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_entity_rename_field_questions_intent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='entidades',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='intent',
        ),
        migrations.AddField(
            model_name='questions',
            name='field',
            field=models.CharField(choices=[('price', 'Price'), ('product_name', 'Product Name'), ('brand', 'Brand'), ('model', 'Model'), ('product_code', 'Product Code'), ('processor', 'Processor'), ('graphics', 'Graphics'), ('hard_disk', 'Hard Disk'), ('ram', 'RAM'), ('screen', 'Screen'), ('battery', 'Battery'), ('warranty', 'Warranty'), ('so_software', 'SO/Software'), ('general', 'General'), ('connections', 'Connections'), ('audio', 'Audio'), ('webcam', 'Webcam'), ('certifications', 'Certifications'), ('packing_size', 'Packing Size'), ('memory_reader', 'Memory Reader'), ('keyboard', 'Keyboard'), ('optical_driver', 'Optical Driver')], default='general', max_length=255),
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
    ]
