from django.db import models

class FieldChoices(models.TextChoices):
    PRICE = 'price', 'Price'
    PRODUCT_NAME = 'product_name', 'Product Name'
    BRAND = 'brand', 'Brand'
    MODEL = 'model', 'Model'
    PRODUCT_CODE = 'product_code', 'Product Code'
    PROCESSOR = 'processor', 'Processor'
    GRAPHICS = 'graphics', 'Graphics'
    HARD_DISK = 'hard_disk', 'Hard Disk'
    RAM = 'ram', 'RAM'
    SCREEN = 'screen', 'Screen'
    BATTERY = 'battery', 'Battery'
    WARRANTY = 'warranty', 'Warranty'
    SO_SOFTWARE = 'so_software', 'SO/Software'
    GENERAL = 'general', 'General'
    CONNECTIONS = 'connections', 'Connections'
    AUDIO = 'audio', 'Audio'
    WEBCAM = 'webcam', 'Webcam'
    CERTIFICATIONS = 'certifications', 'Certifications'
    PACKING_SIZE = 'packing_size', 'Packing Size'
    MEMORY_READER = 'memory_reader', 'Memory Reader'
    KEYBOARD = 'keyboard', 'Keyboard'
    OPTICAL_DRIVER = 'optical_driver', 'Optical Driver'
