# Generated by Django 4.2 on 2025-02-18 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_remove_uploadedpdf_processed_uploadedpdf_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedpdf',
            options={'verbose_name': 'PDF', 'verbose_name_plural': 'PDFs'},
        ),
    ]
